<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_KONTAKTI</name>
   <tag></tag>
   <elementGuidId>75e2393f-d96a-457a-b2c3-3f2abe94cf4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='main-nav']/div/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ceb44d2d-b037-4547-8fa2-caf9c67c011b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/aplikacije/kontakti/</value>
      <webElementGuid>08520efd-72e1-4aa3-b4a2-7636f004efdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KONTAKTI</value>
      <webElementGuid>f74ce3e8-f223-4130-91e9-c0efa419c125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/div[@class=&quot;block&quot;]/ul[1]/li[5]/a[1]</value>
      <webElementGuid>6ad44c19-8884-4dee-845e-c165d224fcf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='main-nav']/div/ul/li[5]/a</value>
      <webElementGuid>769d2af0-2a47-4b3b-aeea-7627edf9eb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'KONTAKTI')])[2]</value>
      <webElementGuid>f0fcb51b-0d67-466a-8bf3-16a2a3b92127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AKADEMIJA FERI'])[2]/following::a[1]</value>
      <webElementGuid>17e9841c-3cf8-4aeb-9652-738c9245b15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAZISKOVANJE'])[2]/following::a[2]</value>
      <webElementGuid>bffadccb-cd80-4b2d-bdba-66dbd3edb8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zapri primarno navigacijo'])[1]/preceding::a[1]</value>
      <webElementGuid>f5ab41e2-571d-42f4-a1e4-26e2a1bd9d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOVICE'])[1]/preceding::a[2]</value>
      <webElementGuid>9d525ede-a6e2-40c7-9398-53f90983cc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/aplikacije/kontakti/')])[2]</value>
      <webElementGuid>72244d1d-1aaa-44e9-bb80-a97e4745fcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nav/div/ul/li[5]/a</value>
      <webElementGuid>e49afa10-5c84-4225-9615-c10b1f7fa40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/aplikacije/kontakti/' and (text() = 'KONTAKTI' or . = 'KONTAKTI')]</value>
      <webElementGuid>171cbc52-44b5-4867-958e-21b4e45bb3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
