<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_prikai</name>
   <tag></tag>
   <elementGuidId>58484715-8196-40fb-af24-d5b214408b0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='e287739656367668']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e287739656367668</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8f7fe5fa-b140-44d3-8d27-718e62aa3393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e287739656367668</value>
      <webElementGuid>5886ca1f-0540-4320-9d57-3d4dd1d97e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>var a=&quot;21LO0tp_6oTNGBnYKxqe.5vjESCkUW-M@8ylQ7Dgds+4IizVwZPrJXAHhfRFac9umb3&quot;;var b=a.split(&quot;&quot;).sort().join(&quot;&quot;);var c=&quot;Jc4ZPsL+Ri3H4AZrBcXLFZ&quot;;var d=&quot;&quot;;for(var e=0;e&lt;c.length;e++)d+=b.charAt(a.indexOf(c.charAt(e)));document.getElementById(&quot;e287739656367668&quot;).innerHTML=&quot;&lt;a href=\&quot;mailto:&quot;+d+&quot;\&quot;>&quot;+d+&quot;&lt;/a>&quot;;</value>
      <webElementGuid>5fc58511-b0c8-4a84-9584-fa360c86c34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[prikaži]</value>
      <webElementGuid>24acdbbc-6c56-4176-92b8-339d35e6aeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e287739656367668&quot;)</value>
      <webElementGuid>b3cdd25d-fd43-4882-b414-d84925dbfaf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='e287739656367668']</value>
      <webElementGuid>bdcb4e6a-096a-45f3-a991-b573164b2df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kontakti']/tbody/tr/td[2]/span</value>
      <webElementGuid>f0f5bbeb-59bb-4910-9665-0dde716165cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brezočnik Lucija'])[1]/following::span[1]</value>
      <webElementGuid>58f5a064-7f75-48cb-8485-356b96fea278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prostor'])[1]/following::span[1]</value>
      <webElementGuid>3f1155e6-850b-4cdb-b157-a125ed4a28f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='G2-1N.11'])[1]/preceding::span[1]</value>
      <webElementGuid>4f3b2d33-524a-4de4-b3c9-fc0e1378b03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gril Lucija'])[1]/preceding::span[1]</value>
      <webElementGuid>b5cff360-6a9f-4984-99eb-218f89a05808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[prikaži]']/parent::*</value>
      <webElementGuid>1325941f-eb7c-48d7-b12b-ad8299d74b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>23d56901-a1e0-4472-9bf5-33b612433623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'e287739656367668' and (text() = '[prikaži]' or . = '[prikaži]')]</value>
      <webElementGuid>a8a910d2-bec9-44c8-af45-333614c483d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
